apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: e-commerce-helm-ingress
spec:
  rules:
  - host: helm-chart.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-svc
            port:
              number: 30009